### ISSUE TITLE
Mise en place de règles de contributions

### ISSUE THREAD

**Issue by baptiste0928** [discordfr/wiki#10]
Bonjour tout le monde ! 👋 

Le projet de wiki en est qu'à ses débuts, mais je le trouve pour l'instant plutôt mal organisé d'un point de vue de la contribution, notamment en l'absence de règles. Tout d'abord, on remarquera **l'absence de README**, ce qui rend le repo peu accueillant, mais surtout **l'absence de licence**. Ce dernier point est particulièrement problématique, car on ne sait pas clairement **ce que l'on a le droit de faire ou non avec le contenu**.

Concernant la contribution, une simple page a été créée sur le site, mais aucune règles n'ont été mises en place, ce qui laisse **les contributeurs dans le flou** et risque même de **casser l'homogénéité du contenu**. Voici pour moi ce qu'il faudrait définir : 

- **La manière d'organiser et de nommer les fichiers.** Il faudrait des règles claires sur la structure des fichiers ainsi que leur nommage. Personnellement, je ne suis pas fan de la structure actuelle, qui nécessite de dérouler deux niveaux de hiérarchie avant d'accéder au contenu. Je verrai plutôt une limitation à un niveau de profondeur, avec des pages classées par niveau de connaissances : les bases, la gestion de serveur, fonctionnalités avancées, ... Nommer les pages (et non les fichiers) de manière moins descriptive serait aussi bien mieux (ex: *Écriture markdown* -> *Formater ses messages (gras, italique, ...)*).

- **La manière d'écrire le contenu.** Comme pour le nommage, il existe plein de manières d'écrire la même chose. Il serait bien de définir quelques règles concernant cela, afin de respecter un style commun.

- **Les images.** Les images étant sous forme de lien, ces dernières peuvent devenir inaccessibles ou hébergées sur un service externe hors de contrôle. Il serait bien de définir un endroit où les stocker (i.discord.fr, ou dans l'idéal un dossier spécial de ce repo). Des règles seraient là encore à définir concernant les captures d'écran (masquer les pseudos ? etc.)

Voilà mes premières remarques, j'espère qu'elles seront utiles ! 😀

**Comment by grifgrif** [comment]
Pour les images elles serons conçues par notre service et Upload, nous utilisons des images avec des pseudos génériques (Discord#0000 par exemple)
En-suite on verra avec le reste de l'équipe (je suis sur tel aussi, pas pratique)

**Comment by IchiiDev** [comment]
Plusieurs informations complémentaires sont à apporter par rapport à cette Issue.

Les guidelines de contribution sont actuellement entrain d'êtres revues, et seront publiées lorsqu'elle seront finies, néanmoins il faut noter certaines règles importantes en attendant:
- Il convient de garder une constance dans la façon de rédiger, il faut pour cela garder en tête que le wiki n'est pas un guide, mais une banque de données pour éclairer les utilisateurs sur le fonctionnement de Discord. Il faut donc éviter de s'adresser directement aux utilisateurs et adopter une approche informative plus que didactique.
- Garder une mise en forme légère et éviter de mettre trop de titres, de sous parties ou inonder l'article d'images.

Pour éclairer les contributeurs sur leurs droits et leurs obligations, nous avons intégré le fichier [LICENSE](https://github.com/discordfr/wiki/blob/master/LICENSE/) pour spécifier à quelles règles se contraindre vis à vis du contenu du wiki. Nous avons également ajouté une template de Pull Request pour garder une constance à l'ouverture de celles-ci.
Comme spécifié plus haut par mon collègue, le service d'images de discord.fr est accessible sur demande à notre equipe, nous sommes également entrain de considérer la création d'une banque d'image et d'assets pour permettre aux contributeurs de rédiger plus rapidement leurs articles. 

Ces changements sont à venir, mon souhait est que cela soit fait le plus vite possible, il faut néanmoins que nous finissions la réorganisation de certaines parties de l'équipe avant d'entreprendre une mise à jour des conditions de rédaction. J'apporterais des updates de la situation dans cette Issue au fur et à mesure que les changements seront faits.

Cordialement,
Ichii, Reviewer et Maintainer du Wiki
