### ISSUE TITLE
Obtenir son identifiant Discord

### ISSUE THREAD

**Issue by dreas222** [discordfr/wiki#127]
Au sein de cette page je souhaite proposer un tutoriel à jour afin d'obtenir son identifiant Discord.
La page pourrait se présenter sous forme d'images étape par étape au départ et finir par un court gif ! 

Pourquoi je propose ce changement ? La redirection amenant vers la solution officielle de Discord (https://go.discord.fr/ID) n'est plus à jour, le mode développeur ne peut s'activer que dans le paramètre "avancé" et non plus 'apparence".

**Comment by Zallom** [comment]
Salut,
Puisque c'est du wiki, le but n'est pas de proposer un tutoriel mais juste une page d'explication sur le mode développeur et sur son utilité ^^

**Comment by dreas222** [comment]
Désolé j'avais pas les mots x))) Pour ça que j'ai parlé de page et de solution après !

**Comment by IchiiDev** [comment]
Au delà de l'identifiant de compte, il y a plusieurs choses importantes qui peuvent être accédées via le mode développeur. Donc la page à son sens si elle aborde tout ce qu'active ce dernier. Je vais ajouter le fichier correspondant, je me chargerais de l'indiquer ici.

**Comment by IchiiDev** [comment]
@dreas222 
Le fichier est créé, voici son lien sur la branche `master`: https://github.com/discordfr/wiki/blob/master/interface/fonctionnalites/mode-developpeur
Il faudra pull le wiki sur votre fork avant de pouvoir le modifier.

**Comment by dreas222** [comment]
C'est noté merci !
