### ISSUE TITLE
DTesters est en pause

### ISSUE THREAD

**Issue by PetitPotiron** [discordfr/wiki#128]
Bonjour, 
Je pense qu'il serait judicieux d'ajouter l'information que le serveur DTesters est en pause ([cet article](https://github.com/discordfr/wiki/blob/master/programmes-communautaires/testeurs/discord-testers.md))

![context](https://user-images.githubusercontent.com/70655051/140795661-f6f06e26-4f9c-449b-b21f-9225cf872bc1.png)

**Comment by IchiiDev** [comment]
Selon les annonces de Solarion, la maintenance était prolongée jusqu'à la fin du mois d'octobre. En absence d'actualisation, je propose d'attendre que Discord update la date ou annonce les changements. Vous pourrez rouvrir cette issue dans ce cas précis.
