### ISSUE TITLE
Création d'un article dédié aux scheduled events

### ISSUE THREAD

**Issue by LukeSkywalkerDev** [discordfr/wiki#132]
Hello,

Je propose la création d'un article sur les scheduled events dans l'optique d'explciiter leur fonctionnement (la manière dont il est possible de créer, modifier ou annuler un évènement, comment en débuter/terminer un...). Le wiki est selon moi le lieu adéquat pour un article à ce sujet, d'autant plus que cet ajout est voué à perdurer.

Cette nouveauté Discord pourrait en effet se révéler intéressante à développer de par sa présence sur tous les serveurs communautaires, mais aussi puisque l'évènement peut se dérouler n'importe où, l'application n'obligeant pas l'évènement à prendre place sur celle-ci, ce qui permet certainement de généraliser son utilisation d'ù l'intérêt de créer un article sur ce sujet.

Ainsi, outre l'enrichissement du wiki, ce nouvel article (que l'on pourrait placer dans [./configuration-serveur/configuration-serveur/](https://github.com/discordfr/wiki/tree/master/configuration-serveur/configuration-serveur)) permettrait d'informer les utilisateurs et de détailler  cette fonctionnalité à travers un article francophone.

**Comment by PetitPotiron** [comment]
Très bonne idée! On pourrait aussi placer cet article dans /outils-communautaires :)

**Comment by LukeSkywalkerDev** [comment]
En effet, bien que les deux emplacements soient possibles, la catégorie dans laquelle tu proposes de placer cet article pourrait être plus adéquate.

**Comment by IchiiDev** [comment]
Merci pour la suggestion ! Vous pouvez dès maintenant contribuer au fichier [Planification d'évenements](https://github.com/discordfr/wiki/blob/master/programmes-communautaires/outils-communautaires/evenements.md). 
Nota bene: *Si vous souhaitez éditer le fichier, il va falloir actualiser votre fork*
