### ISSUE TITLE
Create widget.md

### ISSUE THREAD

**Issue by PetitPotiron** [discordfr/wiki#144]
Bonjour à tous,
La PR (malheureusement non valide) #143 est une bonne idée, ce wiki concernant Discord, il est je pense une bonne idée de rajouter un article concernant les widgets de serveur, dans la catégorie `configuration-serveur`.

**Comment by IchiiDev** [comment]
Je m'en occupe dès que possible !

**Comment by IchiiDev** [comment]
Merci pour la suggestion ! Vous pouvez dès maintenant contribuer au fichier [Les Widgets de Discord](https://github.com/discordfr/wiki/blob/master/configuration-serveur/configuration-serveur/widget.md).
Nota bene: *Si vous souhaitez éditer le fichier, il va falloir actualiser votre fork*

[Lien site](https://discord.fr/wiki/configuration-serveur/configuration-serveur/widget/)
