### ISSUE TITLE
Créer un article sur le developer portal

### ISSUE THREAD

**Issue by b2856203** [discordfr/wiki#147]
Je pense qu'il serait bien de créer une page sur le discord developer portal. Ceci inaugurerait la catégorie "développement"
 actuellement vide.
![image](https://user-images.githubusercontent.com/89143083/148262460-9359d88d-f269-4988-97d2-411464c17a56.png)
Cela aiderait aussi les utilisateurs voulant créer des bots ou autres travaux de développement en rapport avec discord.

**Comment by IchiiDev** [comment]
Cette page sera intégrée avec un batch de plusieurs autres pages dans les prochaines semaines !

**Comment by b2856203** [comment]
D'accord
