### ISSUE TITLE
Mettre à jour la page des embeds

### ISSUE THREAD

**Issue by lieutenantX** [discordfr/wiki#148]
La page wiki des embeds contient plusieurs erreurs :

- [ ]  : La limite pour le contenue est passé de 2048 à 4096 caractères
- [ ]  : le liens hypertexte renvoie vers une image et non pas vers la documentation discord
- [ ]  : Préciser que le nombre total de caractères d'un embed ne doit pas excéder 6 000

[page concernée](https://discord.fr/wiki/interface/salon-textuel/embeds/)

**Comment by grifgrif** [comment]
Merci @lieutenantX !
C'est corrigé, le site sera mis à jour dans la semaine.
Slash FR vous remercie pour votre souci du détail.
