### ISSUE TITLE
Mettre à jour la page des dossiers de serveurs

### ISSUE THREAD

**Issue by PetitPotiron** [discordfr/wiki#151]
J'ai remarqué que c'est article ressemble beaucoup à un tutoriel, il serait judicieux de le transformer en un réel article plus semblable aux autres pages du wiki.

[page concernée](https://discord.fr/wiki/interface/fonctionnalites/dossiers-serveurs/)

**Comment by IchiiDev** [comment]
Je vois que vous avez ouvert une Pull Request (#150) concernant cet article. Vous pouvez effectuer les différents changements dans votre pull request sans avoir à ouvrir une Issue. 👍
