### ISSUE TITLE
Les client test

### ISSUE THREAD

**Issue by Itskleii** [discordfr/wiki#164]
---
title: Les clients test
keywords:
  - Client
  - Discord
  - Test
description: Les différents clients test de Discord
---

# Les clients test de Discord

Discord donne la possibilité à la communauté de tester certaines fonctionnalités en avance, cependant ces clients sont assez instables et contiennent de nombreux [bugs](https://dfr.gd/bugreport).

### Comment y avoir accès sur son ordinateur ?

Sous windows, il existe 3 version utilisable, la version [stable](https://discord.com/download), en d'autre terme, la version classique, la version béta, disponible dans [la page des téléchargements de discord](https://discord.com/download), puis la version [alpha](https://discord.com/api/downloads/distributions/app/installers/latest?platform=win&channel=canary&arch=x86), la moins stable.

### Comment y avoir accès sur un appareil IOS ?

Pour commencer, installer l'application [TestFlight](https://apps.apple.com/us/app/testflight/id899247664), ensuite rendez-vous sur https://dis.gd/testflight pour vous inscrire et installer la béta.

Si vous souhaitez quitter le programme de test, rendez-vous sur [TestFlight](https://apps.apple.com/us/app/testflight/id899247664), recherchez l'application Discord, tout en bas de la page,cliquez sur " arrêter de tester "

![image](https://user-images.githubusercontent.com/84471738/152777242-5fb68066-251a-4032-8db6-95c6326e2bba.png)

### Comment y avoir accès sur un appareil android ?

Afin de rejoindre la **béta** sur android, rendez-vous sur https://play.google.com/apps/testing/com.discord, cliquez sur " devenir testeur ", et suivez les instructions.

![image](https://user-images.githubusercontent.com/84471738/152700070-742e2cdb-cc98-4354-8632-35a695e325e5.png)

Pour rejoindre la version **alpha**, vous devez faire partie de la béta. Puis, vous rendre sur https://groups.google.com/g/discord-android-alpha-testers?pli=1, cliquez sur " rejoindre le groupe ", renseignez les informations demandées, puis cliquez à nouveau sur " rejoindre le groupe ".

![image](https://user-images.githubusercontent.com/84471738/152694383-d7d6d73b-421b-4890-91a5-81970c6f3a21.png)

Pour ne plus faire partie du programme **béta**, vous devez vous rendre sur le Play Store, recherchez l'application Discord, tout en bas de la page, cliquez sur " quitter ".

![image](https://user-images.githubusercontent.com/84471738/152699818-df934cbc-8367-41c8-a28d-225a4a80161d.png)

Pour quitter la version **alpha**, rendez-vous sur https://groups.google.com/g/discord-android-alpha-testers/membership, puis cliquez sur " quittez le groupe ". 

![image](https://user-images.githubusercontent.com/84471738/152699879-379f141e-0d24-481d-8c0b-eae61b8ac6a5.png)

**Comment by LukeSkywalkerDev** [comment]
Salut, 

Il me semble qu'[Ichii t'a suggéré](https://github.com/discordfr/wiki/pull/163#issuecomment-1031907813) d'ouvrir une issue afin de proposer et de justifier la pertinence de l'article que tu souhaites ajouter, il ne faut pas simplement réenvoyer ton article dans un commentaire d'une issue :)
Tu peux t'inspirer de #132 ou de #144 si tu n'as pas d'idée sur la façon de proposer la création d'un article.

**Comment by Itskleii** [comment]
Hello luke, 

Je n'avais pas compris ça comme ça, mais je te remercie de cette précision et je vais le faire de suite
