### ISSUE TITLE
Création d'un article sur les build override 

### ISSUE THREAD

**Issue by Dragrame** [discordfr/wiki#170]
Bonjour. 
Je propose de créer un article sur les build override car ils sont présents sur Discord mais connu de peu de gens alors qu'ils pourraient les rencontrer. 
Cette article pourrait comprendre l'explication de leur utilité, de où il est possible d'en trouver et même comment les reconnaître.
L'article pourrait se trouver dans Programmes communautaire > Testeurs.
Bonne journée.

**Comment by PetitPotiron** [comment]
Hey, 
C'est une bonne idée, surtout que Discord a également rédigé un article là-dessus : [ici](https://support.discord.com/hc/fr/articles/360030114991-Shhhhhhh-).

**Comment by IchiiDev** [comment]
À voir la semaine prochaine à mon retour.

**Comment by IchiiDev** [comment]
https://github.com/discordfr/wiki/blob/master/developpement/build-override.md
