### ISSUE TITLE
Le mode développeur

### ISSUE THREAD

**Issue by PEPSONYT** [discordfr/wiki#171]
Bonjour, 
Je vous propose d'ajouter une page dans la catégorie ``Paramètres du compte`` dédié à l'utilisation et l'activation du mode développeur.

Je vous es créé un exemple ci dessous. 

Bonne journée

PEP'S ON

# Le mode développeur

## Comment activer le mode développeur sur son compte discord ?

> Allez dans les *Paramètres Utilisateurs* , dans l'application Discord. 
> Dans le menu de gauche, cliquez sur la section *Apparence* . 
> Dans *Avancé* , activez l'option *Mode Développeur*.

## A quoi sert exactement le mode développeur ?

Lorsque le mode développeur est activé, vous pouvez copier les valeurs d'ID pour les utilisateurs, les canaux et les serveurs en cliquant avec le bouton droit sur le nom du serveur, le nom du canal ou le nom d'utilisateur et en sélectionnant l'option «Copier l'ID»

## Est-on obligé d'activer le mode développeur ?

> Bien évidemment que **non**.
> Le mode développeur est utile que pour certaines personnes. 
> Si vous ne l'avais pas activé, cela **n'impactera pas** votre expérience sur discord.

**Comment by PetitPotiron** [comment]
Bonjour @PEPSONYT, 

Cette page, bien qu'encore invisible sur le site web, existe déjà sur le dépôt : [ici](https://github.com/discordfr/wiki/blob/master/interface/fonctionnalites/mode-developpeur.md).

Je pense qu'elle apparaîtra bientôt sur le site web.

**Comment by PEPSONYT** [comment]
A oui, effectivement. Je ne l'avais pas vu. Merci beaucoup
