### ISSUE TITLE
[Suggestion]: Création d'un article regroupant les différants serveur officiel de Discord

### ISSUE THREAD

**Issue by Yeikzy** [discordfr/wiki#179]
### Titre de l'article

official-server.md

### Description de l'article

Cet article regrouperais les différants serveur Officiel de Discord avec une description brève et leur lien d'invitation

 

### Avant de valider

- [X] J'ai bien vérifié que l'article n'existait pas déjà, ou n'a pas déjà été suggéré.
- [X] J'ai bien lu et accepté les règles de contribution du Wiki.

**Comment by IchiiDev** [comment]
Je vois ça la semaine prochaine à mon retour

**Comment by Yeikzy** [comment]
> Je vois ça la semaine prochaine à mon retour

Reçu

**Comment by IchiiDev** [comment]
Les articles existent dès maintenant dans la catégorie des programmes communautaires !
<https://github.com/discordfr/wiki/tree/master/programmes-communautaires>
