### ISSUE TITLE
Suppression article "testeurs" 

### ISSUE THREAD

**Issue by Dragrame** [discordfr/wiki#184]
L'article dans la catégorie programme communautaire sur le serveur discord testers devrait selon moi être supprimé puisque les informations ne sont plus à jour. Et comme le nouveau serveur est privé, je ne pense pas qu'il y ai assez de matière pour éditer l'article actuel et en faire quelque chose d'intéressant.

**Comment by IchiiDev** [comment]
Cet article sera déplacé dans une catégorie "archive" à partir de la semaine prochaine. Il sera modifié en conséquence et disponible sous cette appélation.

**Comment by IchiiDev** [comment]
Article archivé
https://discord.fr/wiki/archive/testeurs
