### ISSUE TITLE
[Suggestion]: Ajout de l'article (discord-safety.md)

### ISSUE THREAD

**Issue by Yeikzy** [discordfr/wiki#189]
### Titre de l'article

Discord Safety

### Description de l'article

L'article aurais pour but d'expliquer le fonctionnement de Discord Safety
(Quand le serveur sera relancer)

### Avant de valider

- [X] J'ai bien vérifié que l'article n'existait pas déjà, ou n'a pas déjà été suggéré.
- [X] J'ai bien lu et accepté les règles de contribution du Wiki.

**Comment by IchiiDev** [comment]
Je ne sais pas si l'article serait pertinent à l'heure actuelle vu que le serveur n'a pour le moment rien d'accéssible en public. Aussi, il faudra voir au moment où ça sera le cas si il ne vaudrait pas l'ajouter à l'article de l'écosystème de modération ou créer son article à part entière.

Je vais close l'issue, on la rouvrira au moment où on aura plus d'infos sur Discord Safety 👍
