### ISSUE TITLE
[Suggestion]: Ajouter dans le fichier `badges.mdx` le nouveau badge.

### ISSUE THREAD

**Issue by Yeikzy** [discordfr/wiki#199]
### Titre de l'article

badges.mdx

### Description de l'article

Ajouter un nouvelle Article concernant le nouveau badge, comme ci-dessous: 
![Image](https://i.imgur.com/Ua1gUZw.png)

### Avant de valider

- [X] J'ai bien vérifié que l'article n'existait pas déjà, ou n'a pas déjà été suggéré.
- [X] J'ai bien lu et accepté les règles de contribution du Wiki.

**Comment by IchiiDev** [comment]
Il faudrait plutôt ouvrir une PR pour ça
